### ISSUE TITLE
Apollo 0.29.0 - 0.30.0 failed to build in Travis

### ISSUE THREAD

**Issue by hendyevan** [apollographql/apollo-ios#1332]
Hi, i have an issue in Travis when build my apps using apollo.
<img width="944" alt="Screen Shot 2020-07-28 at 13 45 24" src="https://user-images.githubusercontent.com/982972/88628946-d5ff1980-d0d8-11ea-86ee-e801849a0bee.png">
It's said there is no module `ApolloCore`, but when i run in xcode and archive it using xcode, it went well. No issue arises when using Xcode.

I tried to downgrade to version `0.28.0` and it works well in Travis. No error occured.
Is there any configuration for Travis to build `Apollo` pod?

**Comment by designatednerd** [comment]
Hi! I'm not sure what your build looks like in Travis, but the issue is around a macro that's used by CocoaPods. CocoaPods pulls every sub-spec into a single big library, so we had to add [this macro](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/Bundle%2BHelpers.swift#L2) to tell the compiler not to try to import the `ApolloCore` module when using CocoaPods. It sounds like that macro is getting properly populated when you build/archive locally. 

What's the command you're using to build on Travis?

**Comment by hendyevan** [comment]
This is command from my Travis :

```
language: swift
osx_image: xcode11.5
xcode_project: Project.xcworkspace

cache:
  - bundler
  - cocoapods

before_install:
  - gem install bundler
  - bundle install
  - pod install

jobs:
  allow_failures:
    - env: code-coverage
  include:
    - stage: deploy
      before_script: curl -sL firebase.tools | upgrade=true bash
      script: bundle exec fastlane deploy
      after_success: bundle exec fastlane archive
```

And for my fastlane I'm using `Gym` :
```
private_lane :ios_build do |options|
    scheme = options[:scheme]
    export_method = options[:export_method]
    output_name = options[:output_name]
    key_name = options[:development]

    gym(
      workspace: "Bhinneka.xcworkspace",
      scheme: scheme,
      configuration: scheme,
      silent: true,
      clean: true,
      suppress_xcode_output: false,
      export_method: export_method,
      output_name: output_name,
      xcargs: "ARCHIVE=YES",
      skip_profile_detection: true,
      codesigning_identity: key_name,
      analyze_build_time: true
    )
  end
```
